- name: Add ClickHouse GPG key
  apt_key:
    url: "https://packages.clickhouse.com/deb/clickhouse.key"
    state: present

- name: Add ClickHouse repository
  apt_repository:
    repo: "deb https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse
    update_cache: yes

- name: Install ClickHouse packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ clickhouse_packages }}"

- name: Create ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: '0750'
  loop:
    - "{{ clickhouse_data_dir }}"
    - "{{ clickhouse_log_dir }}"

- name: Configure ClickHouse server
  template:
    src: config.xml.j2
    dest: /etc/clickhouse-server/config.xml
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: '0644'
  notify: restart clickhouse

- name: Configure ClickHouse users
  template:
    src: users.xml.j2
    dest: /etc/clickhouse-server/users.xml
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: '0644'
  notify: restart clickhouse

- name: Start and enable ClickHouse service
  systemd:
    name: clickhouse-server
    state: started
    enabled: yes
    daemon_reload: yes 