---
- name: Configure Kafka
  hosts: kafka
  become: yes
  roles:
    - kafka

- name: Configure Kafka UI
  hosts: web
  become: yes
  roles:
    - kafka_ui

- name: Configure Clickhouse
  hosts: database
  become: yes
  roles:
    - clickhouse 