---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kafka-instance
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      local_tmp: /tmp
  env:
    ANSIBLE_REMOTE_TMP: /tmp
verifier:
  name: ansible 