kafka_version: "3.9.0"
scala_version: "2.13"
kafka_user: "kafka"
kafka_group: "kafka"
kafka_home: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_log_dir: "/var/log/kafka"

# Настройки кластера
kafka_broker_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}"
kafka_listeners: "PLAINTEXT://0.0.0.0:9092"
kafka_advertised_listeners: "PLAINTEXT://{{ ansible_default_ipv4.address }}:9092"
kafka_listener_security_protocol_map: "PLAINTEXT:PLAINTEXT"
kafka_inter_broker_listener_name: "PLAINTEXT"

# Security settings
kafka_allow_everyone_if_no_acl_found: "true"
kafka_authorizer_class_name: "kafka.security.authorizer.AclAuthorizer"
kafka_super_users: "User:ANONYMOUS"

# ZooKeeper настройки
zookeeper_connect: "{% for host in groups['kafka'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
zookeeper_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}"

# Topic configuration
kafka_clickhouse_topic: "clickhouse"
kafka_topic_partitions: 1
kafka_topic_replication: 1 