kafka_version: "3.9.0"
scala_version: "2.13"
kafka_user: "kafka"
kafka_group: "kafka"
kafka_home: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_log_dir: "/var/log/kafka"

# Настройки кластера
kafka_broker_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}"
kafka_listeners: "INTERNAL://:9092,EXTERNAL://{{ ansible_host }}:9093"
kafka_advertised_listeners: "INTERNAL://{{ ansible_host }}:9092,EXTERNAL://{{ ansible_host }}:9093"
kafka_listener_security_protocol_map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
kafka_inter_broker_listener_name: "INTERNAL"

# ZooKeeper настройки
zookeeper_connect: "{% for host in groups['kafka'] %}{{ hostvars[host]['ansible_host'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
zookeeper_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}" 