---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kafka-ui-instance
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible 